### ISSUE TITLE
Method grammar incomplete/wrong

### ISSUE THREAD

**Issue by gomain** [rust-lang/reference#910] opened 2020-12-10 17:59 UTC
The section on [methods](https://github.com/rust-lang/reference/blob/master/src/items/associated-items.md#methods) states this grammar:
> _Method_ :\
> &nbsp;&nbsp; [_FunctionQualifiers_] `fn` [IDENTIFIER]&nbsp;[_Generics_]<sup>?</sup>\
> &nbsp;&nbsp; &nbsp;&nbsp; `(` _SelfParam_ (`,` [_FunctionParam_])<sup>\*</sup> `,`<sup>?</sup> `)`\
> &nbsp;&nbsp; &nbsp;&nbsp; [_FunctionReturnType_]<sup>?</sup> [_WhereClause_]<sup>?</sup>\
> &nbsp;&nbsp; &nbsp;&nbsp; [_BlockExpression_]
>
> _SelfParam_ :\
> &nbsp;&nbsp; [_OuterAttribute_]<sup>\*</sup> ( _ShorthandSelf_ | _TypedSelf_ )
>
> _ShorthandSelf_ :\
> &nbsp;&nbsp;  (`&` | `&` [_Lifetime_])<sup>?</sup> `mut`<sup>?</sup> `self`
>
> _TypedSelf_ :\
> &nbsp;&nbsp; `mut`<sup>?</sup> `self` `:` [_Type_]

and then elaborates that [_Type_] is limited to the following..

```text
P = &'lt S | &'lt mut S | Box<S> | Rc<S> | Arc<S> | Pin<P>
S = Self | P
```
My thoughts... Why use, the nonterminal, _Type_ in the rule of _TypedSelf_? It is clear that only a small subset of _Type_ is allowed here. Suggestion...
> _TypedSelf_ :\
> &nbsp;&nbsp; `mut`<sup>?</sup> `self` `:` [_SelfType_]
> _SelfType_ :\
> &nbsp;&nbsp; (`&` | `&` [_Lifetime_])<sup>?</sup> `mut`<sup>?</sup> [_Self_] | `Box<`[_Self_]`>` | `Rc<`[_Self_]`>` | `Arc<`[_Self_]`>` | `Pin<`[_SelfType_]`>`
> _Self_ :\
> &nbsp;&nbsp; `Self` | [_SelfType_]

then in the example there is this
```rust
impl Example {
    fn via_projection(self: <Example as Trait>::Output) {}
}
```
which was not mentioned in the grammar nor is accepted syntax. Should be removed?

**Comment by ehuss** [comment] 2020-12-10 20:18
The grammar describes the *syntax* of the language, which corresponds to how it is parsed into an AST. This is significant because macros work with the AST.  Semantic validation is done later, such as validating the self type.  In this example, a macro could accept any type in that position, and that would be valid Rust, such as:

```rust
#[cfg(FALSE)]
fn foo(self: ArbitraryThing) {}
```

**Comment by ehuss** [comment] 2021-01-01 21:39
I'm going to close this, as the grammar is defined as intended.  The reference could definitely make this a little clearer, and I opened #916 to track that.

**Closed by ehuss** 2021-01-01 21:39 UTC
