### ISSUE TITLE
Section on Object Safety does not explicitly mention when Self is a type parameter

### ISSUE THREAD

**Issue by jmaargh** [rust-lang/reference#1437] opened 2023-12-13 00:57 UTC
The section on [Object Safety](https://doc.rust-lang.org/reference/items/traits.html#object-safety) defines that concept with a list of bullet points. That list does not include the case when the trait takes `Self` as a type parameter, but that is included as an example below the list.

```rust
// Not object safe if `Self` is a type argument.
```

I suggest adding a bullet of 

> - A generic parameter of this trait, or any of its supertraits, is not specified to be `Self`

together with an expanded example to show that this applies even when `Self: ?Sized`. An example of this in action is `PartialEq` not being object safe.

If I get the thumbs-up I'll make a PR

**Comment by ehuss** [comment] 2023-12-13 01:23
Thanks for the report! Closing as a duplicate of #756. 

Unfortunately I don't understand the rule introduced in https://github.com/rust-lang/rust/pull/22452 well enough to articulate it in English. I'll try pinging the lang team again on Zulip.

**Closed by ehuss** 2023-12-13 01:23 UTC
