### ISSUE TITLE
Incorrect grammar for `BlockExpression`

### ISSUE THREAD

**Issue by eggyal** [rust-lang/reference#1230] opened 2022-06-15 09:31 UTC
The grammar for [`BlockExpression`](https://doc.rust-lang.org/reference/expressions/block-expr.html) is currently given as:

> _BlockExpression_ :
> &nbsp;&nbsp;&nbsp;{
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[_InnerAttribute_](https://doc.rust-lang.org/reference/attributes.html)<sup>*</sup>
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Statements_<sup>?</sup>
> &nbsp;&nbsp;&nbsp;}
> 
> _Statements_ :
> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[_Statement_](https://doc.rust-lang.org/reference/statements.html)<sup>+</sup>
> &nbsp;&nbsp;&nbsp;| [_Statement_](https://doc.rust-lang.org/reference/statements.html)<sup>+</sup> [_ExpressionWithoutBlock_](https://doc.rust-lang.org/reference/expressions.html)
> &nbsp;&nbsp;&nbsp;| [_ExpressionWithoutBlock_](https://doc.rust-lang.org/reference/expressions.html)

According to this grammar, the final operand of a `BlockExpression` (if present) can only be an `ExpressionWithoutBlock`.  But surely this is not correct: it can be any `Expression`—i.e. including an `ExpressionWithBlock`.

For example, using the documented grammar to parse `{{ 0 }}` as a `BlockExpression` would result in the inner `{ 0 }` block being a `Statement` within the outer block rather than its final operand; a consequence of this would be that such a statement must have unit type per the documentation of [Expression statements](https://doc.rust-lang.org/reference/statements.html#expression-statements); and even if a different type was permitted, its value would not be that of the outer block per the documentation of `BlockExpression`.

**Comment by ehuss** [comment] 2022-06-22 21:40
Thanks for the report!  Yea, the grammar isn't quite capturing what the "final operand" is, as answering that is a little complicated.  I believe this is a duplicate of #762, so closing in favor of that.

**Closed as not planned by ehuss** 2022-06-22 21:40 UTC
