### ISSUE TITLE
`Self` receiver does *not* imply `Self: Sized`

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/reference#1445] opened 2024-01-01 03:17 UTC
[The object safety page says](https://doc.rust-lang.org/nightly/reference/items/traits.html#object-safety)

> * All associated functions must either be dispatchable from a trait object or be explicitly non-dispatchable:
>     * Dispatchable functions must:
>         * [...]
>         * Not have a `where Self: Sized` bound (receiver type of `Self` (i.e. `self`) implies this).
>     * Explicitly non-dispatchable functions require:
>         * Have a `where Self: Sized` bound (receiver type of `Self` (i.e. `self`) implies this).

However, [it is not true that a receiver type of `Self` implies `Self: Sized`.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d0fee50714d4b9c7890fe44d7ac0df38)
```rust
// Minimal example; it also can be demonstrated with bounds that
// require `Sized`, like `<G: From<Self>>` say, even without a
// function body
trait Trait {
    // Fails without an explicit `where Self: Sized` bound
    fn method(self) {}
}
```

Accepting `self`-receiving methods as object-safe methods was [a separate consideration from a `Self: Sized` bound in the RFC.](https://rust-lang.github.io/rfcs/0255-object-safety.html#detailed-design)

> This is why all methods that require Self:Sized are exempt from the typical rules. This is also why by-value self methods are permitted, since currently one cannot invoke pass an unsized type by-value (though we consider that a useful future extension).

**Comment by ehuss** [comment] 2024-01-01 15:58
Thanks for the report! I believe this is a duplicate of #1247, so closing in favor of that.

**Closed by ehuss** 2024-01-01 15:58 UTC
