### ISSUE TITLE
types/closure is not accurate. We don't need to use a new variable when capturing a field from a struct

### ISSUE THREAD

**Issue by Prashant-Shekhar-Rao** [rust-lang/reference#1412] opened 2023-10-02 15:38 UTC
>Composite types such as structs, tuples, and enums are always captured entirely, not by individual fields. It may be necessary to borrow into a local variable in order to capture a single field:
```
struct SetVec {
    set: HashSet<u32>,
    vec: Vec<u32>
}

impl SetVec {
    fn populate(&mut self) {
        let vec = &mut self.vec;
        self.set.iter().for_each(|&n| {
            vec.push(n);
        })
    }
}
```
>If, instead, the closure were to use self.vec directly, then it would attempt to capture self by mutable reference. But since self.set is already borrowed to iterate over, the code would not compile.

This means that this code should not compile.
```
use std::collections::HashSet;
struct SetVec {
    set: HashSet<u32>,
    vec: Vec<u32>
}

impl SetVec {
    fn populate(&mut self) {
        
        self.set.iter().for_each(|&n| {
            self.vec.push(n);
        })
    }
}
```
But this code compiles perfectly.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e739bcc43dc34f40ef07235f06c69f63

**Comment by ehuss** [comment] 2023-10-02 15:58
Thanks for the report! The reference hasn't been updated for the 2021 Edition closure capturing. It is being worked on in #1059, but I haven't had a chance to finish it off. You can find more up-to-date documentation at https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html.

Closing as a duplicate of #1066.

**Closed by ehuss** 2023-10-02 15:58 UTC
