### ISSUE TITLE
Incorrect info on closures capturing individual struct fields

### ISSUE THREAD

**Issue by theemathas** [rust-lang/reference#1519] opened 2024-07-01 01:49 UTC
[The reference page on closure types](https://doc.rust-lang.org/reference/types/closure.html#capture-modes) states the following:

> Composite types such as structs, tuples, and enums are always captured entirely, not by individual fields. It may be necessary to borrow into a local variable in order to capture a single field

As of edition 2021, this is not true. See the [edition guide](https://doc.rust-lang.org/edition-guide/rust-2021/disjoint-capture-in-closures.html).

**Comment by ehuss** [comment] 2024-07-01 14:08
Thanks for the report! I believe this is a duplicate of #1066, so closing in favor of that. Coincidentally, I was looking at getting it updated again, so hopefully we'll get some movement.

**Closed by ehuss** 2024-07-01 14:08 UTC
