### ISSUE TITLE
Is the documentation description outdated?

### ISSUE THREAD

**Issue by heisen-li** [rust-lang/reference#1487] opened 2024-03-29 07:36 UTC
The [description here is](https://doc.rust-lang.org/stable/reference/types/closure.html#capture-modes)：

> Composite types such as structs, tuples, and enums are always captured entirely, not by individual fields. It may be necessary to borrow into a local variable in order to capture a single field:

But it should have been done in [RFC 2229](https://github.com/rust-lang/rfcs/blob/master/text/2229-capture-disjoint-fields.md)。

**Comment by ehuss** [comment] 2024-03-29 13:31
Yes, the information still needs to be updated. There is some work in #1059, but it is incomplete.
Closing as a duplicate of #1066.

**Closed by ehuss** 2024-03-29 13:31 UTC
