### ISSUE TITLE
Describe the `= Type` portion of syntax for `TypeParam`/`ConstParam` in `GenericParams`

### ISSUE THREAD

**Issue by bzm3r** [rust-lang/reference#1373] opened 2023-06-28 02:36 UTC
Generic type/constant parameters can be written like so: `<X: MyTrait = MyType>`

But what does `= MyType` mean? This is not mentioned in the article for Generic Parameters in the Rust Reference: https://doc.rust-lang.org/reference/items/generics.html

It is however, described in the Book: https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#default-generic-type-parameters-and-operator-overloading

Should the Reference include a couple of sentences that help a user know what term they ought to search for more information? For example, something like:

> Generic type and constant parameters can specify a default concrete type using the `<GenericType=ConcreteType>` syntax.

**Comment by ehuss** [comment] 2023-06-28 03:32
Thanks for the report! Yea, the default type and const values aren't documented, yet, but they definitely should be. I'm going to close as a duplicate of #24 (and #1159 to some degree), since this is tracked in that issue.

**Closed by ehuss** 2023-06-28 03:32 UTC
